version: '3'

services:
  db:
    build: ./db
    volumes:
      - db_data:/data
    restart: always

  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - db_data:/data
    depends_on:
      - db
    restart: always

volumes:
  db_data: 